services:
  codex-mcp-wrapper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MCP_PORT=8180
    ports:
      - "8180:8180"
    environment:
      - MCP_PORT=8180
    container_name: codex-mcp-wrapper-single
  open-responses-server:
    image: ghcr.io/teabranch/open-responses-server:latest
    environment:
      - PROVIDER_URL=http://codex-mcp-wrapper-single:8180/v1/chat/completions
    ports:
      - "3000:3000"
    depends_on:
      - codex-mcp-wrapper
    container_name: open-responses-server-single
